name: PHP Unit Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

permissions:
  contents: read

jobs:
    php_unit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.4', '8.0', '8.2']
                wp-versions: ['6.7', '6.8']
        name: PHP Unit Test on PHP ${{ matrix.php-versions }} / WP ${{ matrix.wp-versions }}
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - name: Read .node-version
              run: echo "{NODEVERSION}={$(cat .node-version)}" >> $GITHUB_OUTPUT
              id: nodenv
            - name: Setup Node.js (.node-version)
              uses: actions/setup-node@v4
              with:
                  node-version: '${{ steps.nodenv.outputs.NODEVERSION }}'
            - name: Cache multiple paths
              uses: actions/cache@v4
              with:
                  path: vendor
                  key: ${{ runner.os }}-php${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
            - name: Setup PHP ${{ matrix.php-versions }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
            - name: install npm scripts
              run: npm install
            - name: Install Composer Packages
              run: composer install
            - name: Install WP-CLI
              run: |
                  curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
                  chmod +x wp-cli.phar
                  mv wp-cli.phar /usr/local/bin/wp
            - name: Install several WordPress version by wp-env.override.json
              run: WP_ENV_PHP_VERSION=${{ matrix.php-versions }} WP_ENV_CORE=WordPress/WordPress#${{ matrix.wp-versions }} npm run wp-env start --update
            - name: Check WordPress Version
              run: npm run wp-env run cli wp core version
            - name: Build
              run: npm run build
            - name: Start Environment
              run: npx wp-env start && sudo chmod -R 777 ~/wp-env
            - name: Run PHP Unit Test
              run: npm run phpunit
